theme: minima

title: Nieuws.link
email: c.warrel@nieuws.link
description: 
  Het laatste nieuws, zowel landelijk als lokaal. Sport, politiek, binnenlands nieuws, buitenlands nieuws, opmerkelijke berichten, showbizz, tech, je vindt het allemaal hier
show_excerpts: false # set to true to show excerpts on the homepage

timezone: Europe/Amsterdam

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
